### ISSUE TITLE
How similar is this to Faolan's GDExtensionCSharp?

### ISSUE THREAD

**Issue by GeorgeS2019** [Delsin-Yu/GDExtensionSharp#6]
Is this project same aim as that of Faolan's GDExtensionCSharp?
https://github.com/RhubarbVR/GDExtensionCSharp

**Comment by Delsin-Yu** [comment]
I haven't gotten through their repo yet,
This project aims to provide a NativeAot-based binding for GDExtension.
Since NativeAot naturally supports exporting C-style functions, no extra layer is required for locating HostFxr and launching CoreCLR Runtime.

**Comment by GeorgeS2019** [comment]
@Delsin-Yu 

# Is this your aim?

https://github.com/godotengine/godot-proposals/discussions/7024

# 13th Sept 2023 Update
A menu item of Generate C# Bindings has been added
https://github.com/DmitriySalnikov/godot_debug_draw_3d

![notepad++_BItVY8zquj](https://github.com/godotengine/godot-proposals/assets/49812372/2c7d1d82-7c99-4efa-b2c0-ac0d128e8964)

**Comment by GeorgeS2019** [comment]
@Delsin-Yu 
what to u think of this?
https://github.com/godotengine/godot-proposals/issues/8191#issuecomment-1830490771

**Comment by Delsin-Yu** [comment]
It surely helps a lot for Godot-Mono users, please try to not spam the identical message all over the place, I suggest we continue the discussion in #8.
