### ISSUE TITLE
Can your project serve this?

### ISSUE THREAD

**Issue by GeorgeS2019** [Delsin-Yu/GDExtensionSharp#8]
https://github.com/godotengine/godot-proposals/issues/8191#issuecomment-1830490771

The following step could only be done by the **nuget provider** using **a GDExtension C# binding addon**

`godot --dump-extension-api --gdextension` will create each `extension_api-gdextension-Name.json` for each of the GDExtensions. Obviously, it is expected only one e.g. c++ GDExtension is present

**Comment by Delsin-Yu** [comment]
I do not think this is anything related to this project.
This project is focusing on writing GDExtension using C#/.Net8, an alternative to Godot-Mono.
